### ISSUE TITLE
if im going to npm install a component... Where would i Install..

### ISSUE THREAD

**Issue by midascodebreaker** [dolbex/webpack-laravel#3]
Im puzzle a bit coz how can i install a package for example
vuestrap...

there are 2 node_modules folder altogether..

one in the root folder of laravel

2nd is on the root folder of vue project....

Thanks

**Comment by dolbex** [comment]
Correct, you would install any dependencies for the vue project in 

```
resources/assets/js/your-vue-project
```

using

```
npm install vue-strap
```

or 

```
npm install vuestrap
```

(I'm not sure which vuestrap you're using)
