### ISSUE TITLE
where can i house my old webpack.config.js?

### ISSUE THREAD

**Issue by midascodebreaker** [dolbex/webpack-laravel#4]
before im not using this...
all my config in my loaders are in webpack.config.js

now i dont see here a webpack.config.js

are all loaders included by default?

i have a package that i will use ,

vuestrap...

more or less i wont cater the default because there is piece of code for scss

```
themeLoader: {
    themes: ['./resources/assets/sass/theme.scss', './node_modules/vuestrap/theme/bootstrap.scss'],
  },
```

i think that is the only thing i need to add ... since it is a external package...

i think other is as is... looking forward for your reply...

Also i need to know where would i install these other dependencies....

inside my laravel root, or in resources/assets/js/projectname?

your reply is much appreciated

**Comment by dolbex** [comment]
The webpack config is located in 

```
resources/assets/js/your-vue-project/build
```

You would need to alter the webpack base config so it loads during development and production
