### ISSUE TITLE
I have integrated elixir browserify vueify, Must I do step by step install laravel node_modules again?

### ISSUE THREAD

**Issue by cnweibo** [dolbex/webpack-laravel#5]
Hi, 
It is great i find your job. My question is: I have done a lot to make laravel build system to work.(The main module are : -    "laravel-elixir-vueify": "^1.0.3",
-    "laravel-elixir": "^4.0.0", )

Must I re-install again based on your package.json for backend?
What is the difference between the laravel official package.json you have made?
If I only run npm install in the resources/assets/js/vueapp directory, does that will work?
I find it is a painful job everytime i run npm install command.

Thanks~!

**Comment by dolbex** [comment]
This question is a little beyond my scope. I'm not quite sure.
