### ISSUE TITLE
How to integrate this with laravel 5.3

### ISSUE THREAD

**Issue by bogdandevlpr** [dolbex/webpack-laravel#8]
Since laravel 5.3 comes with vue 2 already set up in the resources files. How would we go about getting the development features added in this template? and will this template be updated to laravel 5.3 with vue 2 ?
Thanks!

**Comment by dolbex** [comment]
This is on my agenda for this week.

**Comment by bogdandevlpr** [comment]
That's great to hear :D
Thank you for your response
